"""Build submission documents from validated final evidence, without execution."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[5];HERE=Path(__file__).resolve().parent.parent
data=json.loads((HERE/'final-inventory.json').read_bytes())
selection=json.loads((HERE/'final-selection.json').read_bytes())
caps={'ordinary':10,'positive':55,'negative':60,'nonterminal':45,'terminal':55,'paused-death':15,'active-death':15,'interruption':25}
descriptions={'ordinary':'원래 Gala N=3 public q/v 대조','positive':'한 Gala PID의 S0 → S1 → S2 → S3 FINAL_TERMINAL; CURRENT 이후 resume, 다음 body 차단 관측','negative':'실제 S1/S2 인증 뒤 세 번째 Form 후보를 의도적으로 거부; CURRENT=S2, body4 없음, session STOP','nonterminal':'실제 genesis→S2 replay 중 object/receipt/CURRENT 불변; 첫 S3 receipt만 transition ID, S4는 정상 연결','terminal':'실제 FINAL_TERMINAL replay; 기존 S3 유지, generation/receipt/attachment 증가 없음, body4 없음','paused-death':'실제 paused Gala에서 controller 종료; GDB와 별도 PGID inferior 모두 종료·수거, CURRENT=S0, body2 없음','active-death':'실제 Gala step1 native instruction trace 확인 뒤 controller 종료; 전체 자식 종료·수거, CURRENT=S0, body2 없음','interruption':'실제 CURRENT=S1 직후 exit75; acceptance/checkpoint와 독립 edge 재검증으로 S1 복구, 임의 resume 거부, body2 없음'}
def job(name):return next(j for j in data['guarded_jobs'] if j['path'].replace('\\','/').endswith('/'+name))
lines=['# Verified Driver V1 Task 8 최종 증거 제출','',
 'V1 완료 판정은 설계자의 검토를 기다린다. 승인된 Task8의 실제 Gala 실행, 구현 결함 수정, 정확한 최종 소스 회귀와 fresh 내부 검토 증거를 제출한다. 외부 감사와 전칭·형식·물리적 인증은 수행하지 않았다.',
 '',f"최종 지정 합동 회귀: **{data['regression']['passed']} PASS / 0 FAIL / 0 ERROR / 0 SKIP** = V0 83 + V1/live-chain Tasks1–8 207 + Runtime Trace 선택40. 최종 guarded wall **{job('task8-final02')['wall_seconds']!r}초**, 원래 cap120초 유지. `task8-final02-junit.xml`, `jobs/task8-final02/` 참조.",
 '', '실제 실행 결과는 다음과 같다. 각 디렉터리의 SUMMARY, source-pinset, raw trace, checkpoint, worker report, store object/acceptance, containment receipt와 export hash manifest가 근거다. 캡은 실행 상한이며 측정 wall은 독립 guard가 기록한 값이다.',
 '', '| 실행 | 실제 결과 | Guarded wall / cap (초) | 최종 증거 |','|---|---|---:|---|']
for stage,name in selection['runs'].items():
    wall=job('task8-'+name)['wall_seconds'];assert wall<=caps[stage]
    lines.append(f"| {stage} | PASS — {descriptions[stage]} | {wall:.9f} / {caps[stage]} | [{name}]({name}/SUMMARY.json) |")
lines+=['', 'N=3의 실제 단일 inferior PID는422다. S1과 S2 atomic CURRENT publication 관측 시 GDB의 pause가 증명되고 다음 body marker는 없다. publication monotonic time은 동일 CURRENT를 가리키는 resume 관측보다 앞선다. body2/3 marker의 predecessor ID도 각각 S1/S2와 일치한다. S3는 FINAL_TERMINAL이며 body4는 없다. 원래 대조 실행의 public q/v와 네 binary64 bit pattern이 모두 같다.',
 '', 'N=4 negative는 actual checkpoint/raw를 그대로 두고 세 번째 derived candidate의 Form box를 변경한 뒤 edge/completion 외부 hash를 수리했다. 별도 checker가 SEMANTIC에서 거부한다. 내보낸 negative-02 store는 S2 snapshot을 그대로 보존하고, 이후 nonterminal replay의 새로운 S3/S4와 immutable attachment는 nonterminal-02/result-store에 따로 보존한다. replay proof1/2 시점마다 historical store의 모든 바이트가 그대로임을 확인했다.',
 '', '최종 paused receipt는 GDB797와 별도 PGID의 Gala807, active receipt는 GDB829와 Gala839를 모두 기록한다. 두 receipt 모두 descendant_remaining_pids=[] 및 owned_subtree_verified=true이고, 실제 inferior /proc 항목이 없다. active 시험은 barrier metadata가 생성되기 전 실제 Gala leapfrog native step1 instruction의 complete raw row(seq191)를 보존했다. body2는 시작되지 않았다.',
 '', 'fresh 검토의 구현 결함 네 건을 RED로 보존한 뒤 최소 수정했다. 첫 검토의 prefix mutation 이후 resume, S0 replay-only의 LIVE dispatch, logical Form source ID 누락은 controller/replay만 수정했다. 이어 첫 actual sequence와 328-case 회귀 뒤 최종 검토에서 별도 PGID inferior가 supervisor 종료 판정 밖에 있는 문제를 발견했다. 실제 두 inferior가 죽은 관측만으로 제품의 전체 자식 종료 계약을 충족한다고 판단하지 않았다.',
 '', '별도 group 자식을 생성하는 로컬 TEST_ONLY fixture는 paused/active 모두 2 FAIL을 재현했다. supervisor는 dedicated subreaper의 전체 자식·adopted subtree를 추적하고 start time과 pidfd로 PID 재사용을 구별한다. 전체 자식을 정지시킨 뒤 종료·수거하고, 새 adopted 자식과 모든 추적 identity 부재를 확인한다. launcher도 verified subtree receipt를 요구한다. focused51 PASS 후 globally bound source가 바뀌었으므로 actual8단계와 전체330회귀를 모두 재취득했다. 최종 fresh reviewer는 APPROVE이다. 수정은 승인된 계약의 구현 결함 해결이며 수치·replay-transition·source/token/session/barrier 계약을 넓히지 않았다.',
 '', '`review-fixes.md`, `final-review-01.json`, `containment-fix.md`, `final-review-02.json` 및 RED/GREEN JUnit/stdout/source snapshots를 보존했다. reviewer는 별도 agent로 소스·저장된 증거·hash/JUnit을 읽었고 numerical checker나 실제 실행을 독립 재실행하지 않았다. 이는 fresh 내부 검토이며 외부 감사가 아니다.',
 '', '최초 positive-01은 writer allocation512MiB에 원래 trace reserve512MiB와 사전 receipt6530bytes가 함께 들어가지 않아 S0에서 resource refusal했다. 그 실패는 그대로 보존했다. writer allocation만1GiB로 잡고 trace cap512MiB, storage8GiB, memory4GiB와 per-job wall cap은 유지해 positive-02를 취득했다. 이후 final review 수정으로 positive-03을 취득했다. 이전 Task8 PASS는 이전 binding의 historical evidence로 남기며 최종 소스 PASS로 소급하지 않는다.',
 '',f"최종 V1 source pinset **40개**, SHA256 `{data['source_binding']}`. 이동된 live-chain11/11 및 supervisor가 모두 포함됐다. source-identical 합친 native mirror는 **{data['combined_source_identical_files']}파일**이며 V0-only baseline으로 회귀를 대체하지 않았다. Task7 대비 제품 변경은 {', '.join(data['source_delta_from_task7'])} 네 파일이다.",
 '',f"보호 inventory **7,232개 변경0**, pre-Task8 역사 **{data['histories']['pre_task8']['checked']}개 변경0**, pre-Task7 **{data['histories']['pre_task7']['checked']}개 변경0**, pre-compatibility **{data['histories']['pre_compatibility']['checked']}개 변경0**. V0 승인89파일 map/원본 file SHA `{data['v0_approved_pinset_sha256']}` 유지. V0 gate와 source binding 의미, 기존 Runtime Trace/regular_nstep 소스·계약, V0 receipt/acceptance와 Task4 TEST_ONLY fixture를 변경하지 않았다. export된 최종 실제 증거 {data['exported_evidence_files_verified']}파일 hash를 재검사했다.",
 '',f"기존 ledger의 모든 과거 job 기록과 사용량을 보존하고 승인된 ceiling만3600→4200초로 증액했다. Task8 추가 guarded wall **{data['additional_guarded_wall_seconds']!r}초**, 현재 누적 **{data['used_seconds']!r}/4200초**, 잔여 **{data['remaining_seconds']!r}초**. 실패·검토 수정으로 필요한 RED/GREEN/전체 회귀/actual재실행을 모두 같은 ledger에 반영했다. 원인·대상은 reruns.md에, 각 정확한 wall은 아래 표와 기존 ledger/jobs에 있다. 신규 ledger나 10/100-step·성능·멀티코어·신경망·진화 실험은 없다.",
 '', '| Guarded job | Wall seconds |','|---|---:|']
lines += [f"| {j['path'].replace(chr(92),'/').rsplit('/',1)[1]} | {j['wall_seconds']!r} |" for j in data['guarded_jobs']]
metrics=json.loads((HERE/'positive-03/metrics.json').read_bytes())
lines+=['','실제 N=3 per-barrier 측정값은 다음과 같다. 독립 producer/checker 실행과 sealing/publication 동안 pause한 비용이며 일반 성능 최적화 실험이나 완료시간 예측으로 확장하지 않는다. 초기 acquisition4.896246380999997초, 다음 body acquisition은 각각1.2713560299999926초와1.3166462509999803초다.',
 '', '| Barrier | Produce | Check | Seal | Publication | Paused (초) |','|---|---:|---:|---:|---:|---:|']
for row in metrics:
    if 'step' in row:lines.append('| '+str(row['step'])+' | '+' | '.join(f"{row[k]:.9f}" for k in ('produce_seconds','check_seconds','seal_seconds','publication_seconds','paused_seconds'))+' |')
lines+=['','init-return→step1-entry와 terminal frontier 이후 wrapper tail은 기존 UNTRACED 범위를 유지한다. 검증된 finite numerical bodies와 저장소/실행 순서에 한정한다. 기존 root/GDB/OS trust 가정도 유지한다. arbitrary resume, terminal successor와 일반 cross-session publication은 허용하지 않는다.',
 '', 'Git HEAD `fbbb90171c43ed5462e9584c2621cb0b86b80bd4`, branch `codex/runtime-trace`; index empty, tracked git diff --check exit0. 수정한 untracked 제품/시험도 no-index whitespace 검사를 거친다. 전체 Git status와 정확한 명령/exit/diagnostic은 git-status.txt와 git-verification.json에 제출한다. staging·commit·push 없음. 최종 V1 완료와 외부 acceptance 판정은 설계자가 한다.']
with (HERE/'report.md').open('x',encoding='utf-8',newline='\n') as f:f.write('\n'.join(lines)+'\n')
status=['# Verified Driver V1 현재 상태 — 2026-10-06','',
 '**V1 완료 판정: 설계자의 최종 증거 검토 대기. 외부 감사·전칭/형식/물리적 인증은 수행하지 않았다.**','',
 'Task1–7은 설계자가 완료 처리했다. Task8 승인 범위의 실제 Gala8단계, 필요한 구현 결함 수정, 영향받은 actual증거 재취득, 최종 source-identical 합동 회귀와 fresh 내부 검토 증거를 제출한다. 초기Task8와 검토 RED/REQUEST_CHANGES는 모두 historical evidence로 유지한다. 이전 현재 상태 문서 원본은 verified_driver/v1/artifacts/task8/pre-task8-status.md에 보존했다.','',
 '**최종 지정 합동 회귀330 PASS / 0 FAIL / 0 ERROR / 0 SKIP** = V083 + V1/live-chain207 + Runtime Trace선택40. fresh 내부 reviewer APPROVE.','',
 '실제 N=3 한 PID422가 S0→S1인증→resume→S2인증→resume→S3 FINAL_TERMINAL을 수행하고 원래 Gala public q/v bits와 일치한다. 실제 N=4의 세 번째 후보 거부는 CURRENT=S2, body4부재, STOP을 유지한다. 실제 nonterminal replay 중 historical authority는 바뀌지 않고 첫 후속 S3 receipt만 승인된 immutable replay-transition을 bind한다. FINAL_TERMINAL replay는 generation/receipt/attachment를 만들지 않는다. 실제 paused/active controller 종료는 별도 PGID의 Gala까지 종료·수거하고 body2를 차단한다. 실제 post-CURRENT 중단은 receipt/checkpoint/독립edge 재검증으로 S1을 복구한다.','',
 '검토 수정은 controller/replay의 prefix 및 logical source identity 검증과 replay-only S0 dispatch 차단, supervisor/containment의 전체 owned subtree 종료 판정이다. V0와 기존 수치·replay-transition·live token/session/barrier 계약을 넓히지 않았다.','',
 f"보호7232 변경0, pre-Task8역사340 변경0, pre-Task7역사287 변경0, pre-compatibility역사152 변경0. V0승인89파일 pinset유지, Task4 TEST_ONLY fixture그대로. 최종V1 pinset40파일, 이동11/11 포함, binding `{data['source_binding']}`. 합친 source-identical native mirror188파일.",'',
 f"기존공유 ledger 사용량보존, 승인ceiling4200초. Task8추가 guarded wall {data['additional_guarded_wall_seconds']!r}초; 누적 {data['used_seconds']!r}/4200초, 잔여 {data['remaining_seconds']!r}초. 각 기존 hard cap 유지, 필요한 실패/검토 재실행만 reserve사용. 새 ledger/범위밖실험/staging/commit/push 없음.",'',
 'init-return→step1-entry와 terminal frontier 이후 wrapper tail의 UNTRACED 및 root/GDB/OS trust 가정은 유지한다. Task8finite실행 결과를 전칭/형식/물리적 인증이나 외부감사로 확장하지 않는다.','',
 '제출: verified_driver/v1/artifacts/task8/report.md, final-inventory.json, source-pinset.json, task8-final02-junit.xml, final-review-02.json, final-selection.json, git-status.txt와 git-verification.json.']
(ROOT/'current/VERIFIED_DRIVER_V1_2026-10-06.md').write_text('\n'.join(status)+'\n',encoding='utf-8',newline='\n')
with (ROOT/'.superpowers/sdd/2026-10-06-verified-driver-v1-certified-chain/progress.md').open('a',encoding='utf-8',newline='\n') as f:
    f.write('\nTask8: evidence submitted for designer judgment, no V1 completion declaration. All eight actual Gala stages reacquired on final binding '+data['source_binding']+' after preserved review RED/minimum fixes; combined330/0/0/0, fresh internal APPROVE, protected7232/history340+287+152 unchanged, V0approved89 exact, relocated11/11 pinned. Same ledger ceiling4200, cumulative '+repr(data['used_seconds'])+', remaining '+repr(data['remaining_seconds'])+'. No staging/commit/push; finite/UNTRACED/trust limitations retained. See artifacts/task8/report.md.\n')
print('Report/current status/additive progress saved; designer completion decision pending.')
