"""Gate 2B W1 cause evidence: disassemble the gala functions that the replay T transcribes, from the
exact .so files whose SHA-256 the fixture manifest recorded. Reads files only; runs no gala code.

    python tools/gate2b_disassembly_evidence.py --site-packages <venv312>/lib/python3.12/site-packages
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "benchmarks" / "gate2b" / "fixtures" / "cloud-2026-10-01" / "manifest.json"
OUT = ROOT / "benchmarks" / "gate2b" / "evidence" / "disassembly.txt"
TARGETS = {
    "gala/potential/potential/builtin/cybuiltin.cpython-312-x86_64-linux-gnu.so":
        ["_Z28henon_heiles_gradient_singledPd10double6ptriS0_Pv", "_Z21henon_heiles_gradientdPdS_imS_Pv"],
    "gala/integrate/cyintegrators/leapfrog.cpython-312-x86_64-linux-gnu.so":
        ["_ZL66__pyx_f_4gala_9integrate_13cyintegrators_8leapfrog_c_init_velocityP11_CPotentialmiddPdS1_S1_S1_",
         "_ZL66__pyx_f_4gala_9integrate_13cyintegrators_8leapfrog_c_leapfrog_stepP11_CPotentialmiddPdS1_S1_S1_"],
}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--site-packages", required=True)
    a = ap.parse_args(argv)
    sp = Path(a.site_packages)
    recorded = json.loads(MANIFEST.read_text(encoding="utf-8"))["distribution_files_sha256"]
    ver = subprocess.run(["objdump", "--version"], capture_output=True, text=True, check=True).stdout.splitlines()[0]
    lines = ["# Gate 2B W1 cause evidence (generated by tools/gate2b_disassembly_evidence.py)", f"# {ver}", ""]
    for rel, syms in TARGETS.items():
        h = hashlib.sha256((sp / rel).read_bytes()).hexdigest()
        if h != recorded[rel]:
            raise SystemExit(f"{rel}: sha256 {h} differs from the fixture manifest {recorded[rel]}")
        lines += [f"## {rel}", f"## sha256 {h} (equals fixture manifest)"]
        for s in syms:
            dis = subprocess.run(["objdump", "-d", "--no-show-raw-insn", f"--disassemble={s}", str(sp / rel)],
                                 capture_output=True, text=True, check=True).stdout
            body = [ln for ln in dis.splitlines() if ln.startswith(" ") or ln.endswith(">:")]
            lines += [""] + body + [""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT, hashlib.sha256(OUT.read_bytes()).hexdigest())
    return 0


if __name__ == "__main__":
    sys.exit(main())
